- name: uptime-monitoring installer
  become: true
  hosts: local
  vars_prompt:
    - name: mode
      default: install
      prompt: install / upgrade / uninstall
      private: false
  tasks:
    - name: Gather all services facts
      service_facts:
    - name: Install uptime-monitoring if needed
      include_role:
        name: uptime-installer
      when: mode == "install" and ansible_facts.services['uptime-monitoring.service'] is not defined
    - name: Uninstall uptime-monitoring
      include_role:
        name: uptime-uninstaller
      when: mode == "uninstall" and ansible_facts.services['uptime-monitoring.service'] is defined
    - name: Upgrade uptime-monitoring to version {{version}}
      include_role:
        name: uptime-upgrader
      when: mode == "upgrade" and ansible_facts.services['uptime-monitoring.service'] is defined