- name: debug
  debug:
    msg: "{{ansible_become_password}}"
- name: Clean up uptime-monitoring (if exists)
  command: rm -rf /usr/local/bin/uptime-monitoring
- name: Download uptime-monitoring version {{version}}
  include_tasks: shared-tasks/uptime-downloader.yml
  vars:
    async_time: 300 # 5 minute
    poll_time: 0 # dont wait
- name: Setup database dir
  file:
    path: /var/lib/uptime-monitoring
    mode: '0770'
    owner: debianroot
    group: root
    state: directory
- name: Setup service file
  copy:
    src: ../files/uptime-monitoring.service
    dest: /etc/systemd/system/uptime-monitoring.service
    owner: debianroot
    group: root
- block:
    - name: Check download status
      async_status:
        jid: "{{job_info.ansible_job_id}}"
      register: job_status
      retries: 10
      delay: 5
      until: job_status.finished
  rescue:
    - name: Revert action - remove database dir
      command: rm -rf /var/lib/uptime-monitoring
    - name: Revert action - remove service file
      command: rm /etc/systemd/system/uptime-monitoring.service
    - name: Exit
      fail:
        msg: "Failed downloading uptime-monitoring {{version}}"
- name: Start uptime-monitoring service
  service:
    name: uptime-monitoring
    state: started
    enabled: true
- name: Healthcheck
  uri:
    url: https://uptime.zeroriz.space/api/healthcheck
    method: get
  register: result
  retries: 5
  delay: 3
  until: result.status == 200